variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_DEPTH: 2
  VER: '0.1.0'
  CI_VERSION: '$VER.$CI_PIPELINE_ID'
  IMG_KEEP_MAX: 10

image: gcr.io/kaniko-project/executor:debug-v0.15.0

stages:
  - build_frontend
  - build_backend

workflow:
  rules:
    # Run in a branch where a Containerfile exists, Skip branches in folders
    - if: $CI_PIPELINE_SOURCE == "push" || $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_PIPELINE_SOURCE == "web" || $CI_JOB_MANUAL == "true"
      exists:
        - Containerfile
        - frontend/Containerfile

before_script:
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json

kaniko-build-backend:
  stage: build_backend

  script:
    - 'echo "Image reg name: $CI_REGISTRY_IMAGE"'
    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" || "$CI_COMMIT_BRANCH" == "main" ]]; then
        tag="latest"
        vtag="$CI_COMMIT_SHORT_SHA-$CI_VERSION"
      else
        tag="$CI_COMMIT_REF_SLUG"
        vtag="${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}-${CI_VERSION}"
      fi
      lts=""
      if [[ "$CI_COMMIT_TITLE" =~ .*-lts$ ]]; then
        lts="-lts"
        vtag="$vtag$lts"
      fi
      echo "Running on '$CI_COMMIT_BRANCH': tag = $tag, vtag = $vtag"

    # Build with commit sha
    - /kaniko/executor --cache --context $CI_PROJECT_DIR --build-arg GITLAB_PACKAGE_REGISTRY_TOKEN=$CI_JOB_TOKEN --dockerfile $CI_PROJECT_DIR/Containerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

  retry: 2


kaniko-build-frontend:
  stage: build_frontend
  only:
    changes:
      - frontend/**/*
  script:
    - 'echo "Image reg name: $CI_REGISTRY_IMAGE"'

    - |
      if [[ "$CI_COMMIT_BRANCH" == "master" || "$CI_COMMIT_BRANCH" == "main" ]]; then
        tag="latest"
        vtag="$CI_COMMIT_SHORT_SHA-$CI_VERSION"
      else
        tag="$CI_COMMIT_REF_SLUG"
        vtag="${CI_COMMIT_REF_SLUG}_${CI_COMMIT_SHORT_SHA}-${CI_VERSION}"
      fi
      lts=""
      if [[ "$CI_COMMIT_TITLE" =~ .*-lts$ ]]; then
        lts="-lts"
        vtag="$vtag$lts"
      fi
      echo "Running on '$CI_COMMIT_BRANCH': tag = $tag, vtag = $vtag"

    # Build with commit sha
    - /kaniko/executor --cache --context $CI_PROJECT_DIR/frontend --dockerfile $CI_PROJECT_DIR/frontend/Containerfile --destination $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_TAG --build-arg GITLAB_PACKAGE_REGISTRY_TOKEN=$CI_JOB_TOKEN
  retry: 2